const louvre = { zh: "卢浮宫，巴黎", en: "Musée du Louvre, Paris", fr: "Musée du Louvre, Paris" };

export const featuredWorks = [
  {
    id: "liberty-leading-people",
    featured: true,
    image: "./assets/artworks/liberty-leading-people.jpg",
    source: "https://collections.louvre.fr/en/ark:/53355/cl010065872",
    date: "1830",
    category: "history",
    medium: { zh: "布面油画", en: "Oil on canvas", fr: "Huile sur toile" },
    dimensions: "260 × 325 cm",
    collection: louvre,
    title: { zh: "自由引导人民", en: "Liberty Leading the People", fr: "La Liberté guidant le peuple" },
    summary: {
      zh: "德拉克洛瓦在1830年七月革命后数月内完成此画。他没有复原某一条街垒，而是把真实的巴黎人、尸体与寓言化的“自由”压缩进同一场向前推进的公共记忆。",
      en: "Delacroix painted this within months of the July Revolution of 1830. Rather than reconstructing one barricade, he compressed real Parisians, corpses, and an allegorical Liberty into a shared memory advancing toward the viewer.",
      fr: "Delacroix peint ce tableau dans les mois qui suivent la révolution de Juillet 1830. Au lieu de reconstituer une barricade précise, il condense Parisiens réels, cadavres et Liberté allégorique dans une mémoire collective qui avance vers le spectateur.",
    },
    analysis: {
      zh: "尸体构成近景门槛，人群沿金字塔上升至三色旗。蓝、白、红不是附加的国家标志，而是在服装、烟雾和旗帜之间反复接力；自由女神同时具有古典裸体、劳动者身体与街头行动者的矛盾身份。",
      en: "Corpses form a threshold in the foreground, while the crowd rises in a pyramid to the tricolour. Blue, white, and red pass between clothes, smoke, and flag rather than merely decorating the scene; Liberty combines the contradictory bodies of classical nude, worker, and street insurgent.",
      fr: "Les cadavres forment un seuil au premier plan, tandis que la foule monte en pyramide vers le drapeau tricolore. Bleu, blanc et rouge circulent entre vêtements, fumée et étendard ; la Liberté réunit les corps contradictoires du nu antique, de la travailleuse et de l’insurgée.",
    },
    context: {
      zh: "它常被当作德拉克洛瓦政治激进主义的证明，但画家本人并未参加街垒战，后来的立场也趋于保守。作品的展出与入藏经历反复受政局影响，说明它既是革命图像，也是国家难以稳定安置的政治对象。",
      en: "The painting is often treated as proof of Delacroix’s political radicalism, although he did not fight on the barricades and later became more conservative. Its unstable history of display and storage shows that it was both an image of revolution and a political object the state struggled to place.",
      fr: "Le tableau est souvent pris pour la preuve du radicalisme politique de Delacroix, bien qu’il n’ait pas combattu sur les barricades et qu’il soit devenu plus conservateur. Son histoire mouvementée d’exposition et de réserve en fait à la fois une image de révolution et un objet politique difficile à stabiliser pour l’État.",
    },
  },
  {
    id: "barque-dante",
    featured: true,
    image: "./assets/artworks/barque-dante.jpg",
    source: "https://collections.louvre.fr/ark:/53355/cl010065871",
    date: "1822",
    category: "literature",
    medium: { zh: "布面油画", en: "Oil on canvas", fr: "Huile sur toile" },
    dimensions: "189 × 241.5 cm",
    collection: louvre,
    title: { zh: "但丁之舟", en: "The Barque of Dante", fr: "La Barque de Dante" },
    summary: {
      zh: "这是二十四岁的德拉克洛瓦第一次参加沙龙的宣言之作：但丁与维吉尔乘船穿过地狱之城狄斯周围的沼泽，被愤怒的亡魂包围。文学文本被转译成皮肤、火光、水与恐惧的物质冲突。",
      en: "Delacroix’s Salon debut at twenty-four was a declaration: Dante and Virgil cross the marsh around the infernal city of Dis while wrathful souls engulf their boat. A literary text becomes a material collision of flesh, fire, water, and fear.",
      fr: "Pour sa première apparition au Salon, à vingt-quatre ans, Delacroix choisit un manifeste : Dante et Virgile traversent le marais qui entoure la cité infernale de Dité, assaillis par les âmes coléreuses. Le texte littéraire devient conflit matériel de chairs, de feu, d’eau et de peur.",
    },
    analysis: {
      zh: "舟身的摇摆把稳定的古典构图推向失衡。亡魂身体借鉴米开朗基罗与鲁本斯，但水珠上的并置色点已显示德拉克洛瓦把色彩当作光学振动，而不只是物体的固有颜色。",
      en: "The rocking hull drives a classical arrangement toward imbalance. The damned bodies recall Michelangelo and Rubens, yet the juxtaposed colour notes in droplets already show Delacroix treating colour as optical vibration rather than a fixed property of objects.",
      fr: "Le balancement de la barque pousse l’ordonnance classique vers le déséquilibre. Les damnés rappellent Michel-Ange et Rubens, mais les touches juxtaposées des gouttes d’eau montrent déjà une couleur pensée comme vibration optique plutôt que comme propriété fixe des objets.",
    },
    context: {
      zh: "这幅画既挑战新古典主义的清晰秩序，又在沙龙被国家购藏。因此“浪漫主义反抗学院”的简单故事并不够：德拉克洛瓦从一开始就在制度认可、传统大师与形式冒险之间工作。",
      en: "The painting challenged neoclassical clarity yet was purchased by the state at the Salon. A simple story of Romantic rebellion against the academy is therefore inadequate: Delacroix worked from the start between institutional recognition, old masters, and formal risk.",
      fr: "Le tableau défie la clarté néoclassique, mais l’État l’achète au Salon. Le récit d’une révolte romantique contre l’Académie ne suffit donc pas : dès le début, Delacroix travaille entre reconnaissance institutionnelle, maîtres anciens et risque formel.",
    },
  },
  {
    id: "massacre-chios",
    featured: true,
    image: "./assets/artworks/massacre-chios.jpg",
    source: "https://collections.louvre.fr/ark:/53355/cl010065870",
    date: "1824",
    category: "history",
    medium: { zh: "布面油画", en: "Oil on canvas", fr: "Huile sur toile" },
    dimensions: "419 × 354 cm",
    collection: louvre,
    title: { zh: "希俄斯岛的屠杀", en: "The Massacre at Chios", fr: "Scènes des massacres de Scio" },
    summary: {
      zh: "作品回应希腊独立战争中1822年的希俄斯惨案，并在1824年沙龙与欧洲亲希腊舆论相遇。德拉克洛瓦取消了拯救者与胜利中心，只留下等待死亡或被奴役的家庭。",
      en: "The painting responds to the 1822 massacre on Chios during the Greek War of Independence and entered the philhellenic climate of the 1824 Salon. Delacroix removes both rescuer and victorious centre, leaving families who await death or enslavement.",
      fr: "Le tableau répond au massacre de Chios de 1822, pendant la guerre d’indépendance grecque, et rencontre le philhellénisme européen au Salon de 1824. Delacroix supprime sauveur et centre victorieux : ne restent que des familles attendant la mort ou l’esclavage.",
    },
    analysis: {
      zh: "人物像断裂的柱群贴近画面，空旷地平线却把灾难延伸到远方。右侧骑兵的高度与受害者瘫软、下坠的身体形成支配关系；鲜亮衣料和病弱肤色迫使“美”与灾难同处。",
      en: "Figures press against the surface like broken columns while the open horizon extends catastrophe into the distance. The mounted figure dominates collapsing bodies; brilliant fabrics and sickened flesh force beauty and disaster to occupy the same field.",
      fr: "Les figures se pressent contre la surface comme des colonnes brisées, tandis que l’horizon ouvert prolonge la catastrophe au loin. Le cavalier domine les corps affaissés ; étoffes éclatantes et chairs malades contraignent beauté et désastre à partager le même champ.",
    },
    context: {
      zh: "画作把当代新闻提升为历史画，也参与了欧洲将“希腊受难者”与“奥斯曼暴力者”对置的亲希腊想象。观看同情必须与这种政治化、东方主义化的角色分配一起分析。",
      en: "The work elevated current events to history painting, while participating in a philhellenic opposition between Greek victim and Ottoman aggressor. Its invitation to sympathy must be analysed together with that politicised, Orientalist distribution of roles.",
      fr: "L’œuvre élève l’actualité au rang de peinture d’histoire, tout en participant à l’opposition philhellène entre victime grecque et agresseur ottoman. L’appel à la compassion doit être analysé avec cette distribution politique et orientaliste des rôles.",
    },
  },
  {
    id: "death-sardanapalus",
    featured: true,
    image: "./assets/artworks/death-sardanapalus.jpg",
    source: "https://collections.louvre.fr/en/ark:/53355/cl010065757",
    date: "1827",
    category: "literature",
    medium: { zh: "布面油画", en: "Oil on canvas", fr: "Huile sur toile" },
    dimensions: "392 × 496 cm",
    collection: louvre,
    title: { zh: "萨达那帕拉之死", en: "The Death of Sardanapalus", fr: "La Mort de Sardanapale" },
    summary: {
      zh: "德拉克洛瓦依据拜伦戏剧及相关古代叙述，表现亚述君主在败亡前命令毁掉财宝、马匹与侍妾。画面不是“死亡瞬间”，而是一场由躺卧统治者观看并发动的系统性毁灭。",
      en: "Drawing on Byron’s drama and related ancient accounts, Delacroix shows an Assyrian ruler ordering the destruction of treasures, horses, and concubines before defeat. This is less a single death than a system of annihilation set in motion and watched by the reclining sovereign.",
      fr: "À partir du drame de Byron et de récits antiques, Delacroix montre le souverain assyrien ordonnant, avant sa défaite, la destruction de ses trésors, de ses chevaux et de ses concubines. Ce n’est pas une mort unique, mais un système d’anéantissement déclenché et regardé par le monarque couché.",
    },
    analysis: {
      zh: "红色床榻如倾斜舞台，把刀刃、扭转身体、珠宝和马首卷进连续的阿拉伯式曲线。空间拒绝清楚分层：观看者必须在奢华细节与暴力整体之间不断失焦、重新定位。",
      en: "The red bed acts as a tilted stage, sweeping blades, twisting bodies, jewels, and horse’s head into a continuous arabesque. Space refuses clear hierarchy, making the viewer oscillate between luxurious detail and the total structure of violence.",
      fr: "Le lit rouge agit comme une scène inclinée qui entraîne lames, corps tordus, bijoux et tête de cheval dans une arabesque continue. L’espace refuse toute hiérarchie claire et oblige le regard à osciller entre détail luxueux et structure globale de la violence.",
    },
    context: {
      zh: "1827—1828年沙龙的严厉批评几乎损害其职业前途，后来它却成为浪漫主义的典型。今天仍需追问：作品在批判专制暴力的同时，是否也以女性身体和“东方暴君”想象制造了可供凝视的奇观？",
      en: "Harsh criticism at the Salon of 1827–28 nearly damaged Delacroix’s career, though the picture later became an emblem of Romanticism. It still demands a question: while condemning despotic violence, does it turn women’s bodies and the fantasy of an ‘Oriental tyrant’ into spectacle?",
      fr: "La critique sévère du Salon de 1827-1828 manque de briser sa carrière, avant que le tableau ne devienne un emblème romantique. Une question demeure : en condamnant la violence despotique, transforme-t-il aussi les corps féminins et le fantasme du « tyran oriental » en spectacle ?",
    },
  },
  {
    id: "greece-missolonghi",
    featured: true,
    image: "./assets/artworks/greece-missolonghi.jpg",
    source: "https://www.musba-bordeaux.fr/en/greece-ruins-missolonghi",
    date: "1826",
    category: "history",
    medium: { zh: "布面油画", en: "Oil on canvas", fr: "Huile sur toile" },
    dimensions: "213 × 142 cm",
    collection: { zh: "波尔多美术馆，波尔多", en: "Musée des Beaux-Arts de Bordeaux", fr: "Musée des Beaux-Arts de Bordeaux" },
    title: { zh: "希腊立于迈索隆吉翁废墟", en: "Greece on the Ruins of Missolonghi", fr: "La Grèce sur les ruines de Missolonghi" },
    summary: {
      zh: "迈索隆吉翁在1826年陷落后，德拉克洛瓦让“希腊”化身为跪立在废墟上的女性。作品当年在为希腊事业筹款的展览中出现，使历史画直接进入同时代公共动员。",
      en: "After the fall of Missolonghi in 1826, Delacroix personified Greece as a woman kneeling upright on the ruins. Shown that year in an exhibition supporting the Greek cause, the painting brought history painting directly into contemporary mobilisation.",
      fr: "Après la chute de Missolonghi en 1826, Delacroix personnifie la Grèce en femme agenouillée sur les ruines. Présentée la même année dans une exposition en faveur de la cause grecque, l’œuvre fait entrer la peinture d’histoire dans la mobilisation contemporaine.",
    },
    analysis: {
      zh: "近乎正面的女性身体像纪念碑般竖起，张开的双臂却不是胜利，而是哀悼与暴露。白衣、蓝袍和血色痕迹在狭长画幅中凝结为旗帜般的色彩结构，废墟下伸出的手让寓言重新落回尸体。",
      en: "The nearly frontal woman rises like a monument, yet her open arms signify mourning and exposure rather than victory. White dress, blue mantle, and traces of blood form a flag-like structure, while a hand emerging from the ruins returns allegory to the body.",
      fr: "La femme presque frontale s’élève comme un monument, mais ses bras ouverts disent le deuil et la vulnérabilité, non la victoire. Robe blanche, manteau bleu et traces de sang composent une structure de drapeau ; une main surgissant des ruines rend l’allégorie au corps.",
    },
    context: {
      zh: "德拉克洛瓦从未到过希腊；这是一幅由巴黎新闻、诗歌与亲希腊运动共同塑造的政治寓言。它为受难者发声，也把复杂战争压缩为可被欧洲观众识别的女性国家身体。",
      en: "Delacroix never travelled to Greece. This political allegory was shaped by Parisian news, poetry, and philhellenic activism. It speaks for victims while compressing a complex war into a feminised national body legible to European viewers.",
      fr: "Delacroix n’est jamais allé en Grèce. Cette allégorie politique naît des nouvelles parisiennes, de la poésie et du mouvement philhellène. Elle parle pour les victimes tout en condensant une guerre complexe dans un corps national féminisé, lisible par le public européen.",
    },
  },
  {
    id: "women-algiers",
    featured: true,
    image: "./assets/artworks/women-algiers.jpg",
    source: "https://collections.louvre.fr/ark:/53355/cl010065869",
    date: "1834",
    category: "travel",
    medium: { zh: "布面油画", en: "Oil on canvas", fr: "Huile sur toile" },
    dimensions: "180 × 229 cm",
    collection: louvre,
    title: { zh: "阿尔及利亚妇女", en: "Women of Algiers in Their Apartment", fr: "Femmes d’Alger dans leur appartement" },
    summary: {
      zh: "1832年北非旅程结束前，德拉克洛瓦在法国占领不久的阿尔及尔短暂停留，并获得一次罕见的家庭内部观看机会。两年后的沙龙画并非现场记录，而是素描、记忆、模特与工作室重构的复合物。",
      en: "Near the end of his 1832 North African journey, Delacroix briefly visited newly occupied Algiers and gained rare access to a domestic interior. The Salon painting made two years later is not a direct record but a composite of sketches, memory, models, and studio reconstruction.",
      fr: "À la fin de son voyage nord-africain de 1832, Delacroix séjourne brièvement dans Alger récemment occupée et accède exceptionnellement à un intérieur domestique. Le tableau du Salon, peint deux ans plus tard, combine croquis, mémoire, modèles et reconstruction d’atelier plutôt qu’il ne livre un relevé direct.",
    },
    analysis: {
      zh: "低矮横向空间减弱了戏剧动作，让观看集中在毯面、陶器、珠宝与肤色之间的色彩回响。左侧三人形成沉静节奏，右侧离开的黑人侍女既打开空间，也揭示这个“闲适室内”依赖的劳动与等级。",
      en: "The low horizontal interior suppresses dramatic action, concentrating attention on chromatic echoes among carpets, ceramics, jewellery, and flesh. Three seated women form a quiet rhythm; the departing Black servant opens the space while exposing the labour and hierarchy sustaining this ‘leisurely’ room.",
      fr: "L’intérieur bas et horizontal réduit l’action dramatique au profit des échos colorés entre tapis, céramiques, bijoux et carnations. Les trois femmes assises forment un rythme calme ; la servante noire qui s’éloigne ouvre l’espace tout en révélant le travail et la hiérarchie qui soutiennent ce « loisir ».",
    },
    context: {
      zh: "这不是脱离历史的“后宫真实面貌”。进入空间的条件与法国殖民占领相连，女性的姓名和声音又未进入画面记录。它既保存了德拉克洛瓦极重要的色彩经验，也制造了影响深远的东方主义室内范式。",
      en: "This is not a timeless or transparent view of a harem. Access was entangled with French colonial occupation, while the women’s names and voices disappeared from the record. The painting preserves a decisive colour experience and constructs an enduring Orientalist interior.",
      fr: "Ce n’est ni un harem hors du temps ni une vue transparente. Les conditions d’accès sont liées à l’occupation coloniale française, tandis que les noms et les voix des femmes disparaissent. Le tableau conserve une expérience décisive de la couleur et construit un modèle durable de l’intérieur orientaliste.",
    },
  },
  {
    id: "jewish-wedding-morocco",
    featured: true,
    image: "./assets/artworks/jewish-wedding-morocco.jpg",
    source: "https://collections.louvre.fr/ark:/53355/cl010065868",
    date: "1839",
    category: "travel",
    medium: { zh: "布面油画", en: "Oil on canvas", fr: "Huile sur toile" },
    dimensions: "105 × 140.5 cm",
    collection: louvre,
    title: { zh: "摩洛哥犹太婚礼", en: "Jewish Wedding in Morocco", fr: "Noce juive dans le Maroc" },
    summary: {
      zh: "德拉克洛瓦在1832年丹吉尔旅程中参加犹太家庭婚礼，七年后才将速写与记忆组织为油画。画中重点不是新娘肖像，而是庭院里音乐、舞蹈、交谈和观看共同形成的社会空间。",
      en: "Delacroix attended a Jewish family wedding in Tangier in 1832 and organised sketches and memories into this painting seven years later. The focus is not a bridal portrait but a social space made by music, dance, conversation, and looking.",
      fr: "Delacroix assiste à un mariage dans une famille juive de Tanger en 1832, puis organise croquis et souvenirs en peinture sept ans plus tard. Le centre n’est pas le portrait de la mariée, mais un espace social produit par musique, danse, conversation et regards.",
    },
    analysis: {
      zh: "门框、台阶和廊柱把拥挤人群分成多层舞台；白墙上的光使红、绿、蓝和金色衣饰像音符一样间隔出现。局部笔触松动，整体建筑秩序却异常清楚，形成“即兴”与长期构思的张力。",
      en: "Doorways, steps, and columns divide the crowd into layered stages. Light on white walls spaces red, green, blue, and gold garments like musical notes. Loose local handling sits within unusually clear architecture, creating tension between improvisation and long construction.",
      fr: "Portes, marches et colonnes répartissent la foule en scènes superposées. Sur les murs blancs, la lumière espace les vêtements rouges, verts, bleus et or comme des notes. La touche locale est libre, l’architecture très construite : l’improvisation apparente résulte d’un long travail.",
    },
    context: {
      zh: "本-希莫尔家族及翻译网络使这次进入成为可能，因此作品比匿名“东方场景”更具体；但沙龙标题和说明仍把复杂的摩洛哥犹太生活转交给法国观众的分类体系。应同时保留相遇的具体性与观看权力的不对等。",
      en: "The Ben-Chimol family and networks of interpretation made this access possible, giving the work more specificity than an anonymous ‘Oriental scene’. Yet its Salon framing still translated Moroccan Jewish life into French categories. Encounter and unequal power of observation must be kept together.",
      fr: "La famille Ben-Chimol et les réseaux d’interprètes rendent cet accès possible, donnant à l’œuvre plus de précision qu’une « scène orientale » anonyme. Mais le cadre du Salon traduit encore la vie juive marocaine dans des catégories françaises. Il faut tenir ensemble rencontre concrète et inégalité du regard.",
    },
  },
  {
    id: "crusaders-constantinople",
    featured: true,
    image: "./assets/artworks/crusaders-constantinople.jpg",
    source: "https://collections.louvre.fr/en/ark:/53355/cl010065702",
    date: "1840—1841",
    category: "history",
    medium: { zh: "布面油画", en: "Oil on canvas", fr: "Huile sur toile" },
    dimensions: "411 × 497 cm",
    collection: louvre,
    title: { zh: "十字军进入君士坦丁堡", en: "Entry of the Crusaders into Constantinople", fr: "L’Entrée des croisés à Constantinople" },
    summary: {
      zh: "这件为凡尔赛宫十字军厅订制的巨幅历史画表现1204年第四次十字军攻入基督教城市君士坦丁堡。德拉克洛瓦没有只画凯旋队列，而让获胜者面对跪地求恕的市民、尸体与燃烧的城市。",
      en: "Commissioned for the Crusades Rooms at Versailles, this vast history painting depicts the Fourth Crusade entering the Christian city of Constantinople in 1204. Delacroix does not offer a simple triumph: victors confront pleading citizens, corpses, and a burning city.",
      fr: "Commandée pour les salles des Croisades à Versailles, cette immense peinture d’histoire représente l’entrée de la quatrième croisade dans la ville chrétienne de Constantinople en 1204. Delacroix refuse le triomphe simple : les vainqueurs font face aux suppliants, aux cadavres et à la ville en feu.",
    },
    analysis: {
      zh: "骑马首领形成高位水平线，俯身市民则以连锁曲线滑向前景。甲胄、丝绸、旗帜和远处建筑将权力转化为闪烁色面；壮阔全景与近处的人体屈辱彼此抵消。",
      en: "Mounted leaders establish a high horizon while a chain of bending citizens descends into the foreground. Armour, silk, banners, and distant architecture turn power into flickering colour; panoramic grandeur is checked by bodily humiliation close at hand.",
      fr: "Les chefs à cheval établissent une ligne haute, tandis qu’une chaîne de citadins courbés descend vers le premier plan. Armures, soies, bannières et architectures transforment le pouvoir en surfaces vibrantes ; la grandeur panoramique est contredite par l’humiliation des corps proches.",
    },
    context: {
      zh: "官方委托本意是服务七月王朝的历史工程与十字军记忆，作品却把征服的代价带入中心。它不等于现代意义上的反战画，但显示德拉克洛瓦如何在国家订件内部制造胜利叙事的不安。",
      en: "The royal commission served the July Monarchy’s historical programme and memory of the Crusades, yet the cost of conquest occupies the centre. It is not a modern anti-war painting, but it shows Delacroix unsettling a victory narrative from inside an official commission.",
      fr: "La commande royale sert le programme historique de la monarchie de Juillet et la mémoire des croisades, mais le coût de la conquête occupe le centre. Ce n’est pas un tableau pacifiste au sens moderne ; Delacroix inquiète cependant le récit victorieux de l’intérieur même d’une commande officielle.",
    },
  },
  {
    id: "sultan-morocco",
    featured: true,
    image: "./assets/artworks/sultan-morocco.jpg",
    source: "https://musees-occitanie.fr/oeuvre/moulay-abd-er-rahman-sultan-du-maroc-sortant-de-son-palais-de-meknes/",
    date: "1845",
    category: "travel",
    medium: { zh: "布面油画", en: "Oil on canvas", fr: "Huile sur toile" },
    dimensions: "377 × 340 cm",
    collection: { zh: "奥古斯坦博物馆，图卢兹", en: "Musée des Augustins, Toulouse", fr: "Musée des Augustins, Toulouse" },
    title: { zh: "摩洛哥苏丹与随从", en: "The Sultan of Morocco and His Entourage", fr: "Le Sultan du Maroc et son entourage" },
    summary: {
      zh: "1832年随外交使团访问摩洛哥时，德拉克洛瓦在梅克内斯见到苏丹穆莱·阿卜杜勒-拉赫曼。十三年后，他将现场笔记发展为自己最大型的北非题材作品，并送交1845年沙龙。",
      en: "Travelling with a diplomatic mission in 1832, Delacroix saw Sultan Moulay Abd-er-Rahman at Meknes. Thirteen years later he developed his notes into his largest North African painting and sent it to the Salon of 1845.",
      fr: "Lors de la mission diplomatique de 1832, Delacroix voit le sultan Moulay Abd-er-Rahman à Meknès. Treize ans plus tard, il développe ses notes dans son plus grand tableau nord-africain, présenté au Salon de 1845.",
    },
    analysis: {
      zh: "白马与白衣把苏丹凝结为画面最亮的核心，城门的垂直结构和随从的弧形队列控制着宏大尺幅。颜色并未让场面陷入混乱，而是以绿、红、赭色逐层确认等级和空间距离。",
      en: "White horse and white garments make the sultan the painting’s brightest core. The vertical gate and curving entourage discipline the monumental format; green, red, and ochre articulate rank and distance rather than dissolve the scene into colouristic disorder.",
      fr: "Le cheval blanc et les vêtements clairs font du sultan le noyau lumineux du tableau. La porte verticale et la courbe de l’entourage disciplinent le format monumental ; verts, rouges et ocres articulent rangs et distances au lieu de dissoudre la scène.",
    },
    context: {
      zh: "作品来自真实会见，却不是中性的外交照片：它由法国使团的观看位置、十三年的记忆加工和沙龙历史画规范共同塑造。苏丹的庄严主体性与欧洲对摩洛哥权力的分类凝视同时存在。",
      en: "The work derives from an actual audience but is no neutral diplomatic record. It is shaped by the French mission’s viewpoint, thirteen years of remembered reconstruction, and Salon history-painting conventions. The sultan’s commanding presence coexists with a European gaze classifying Moroccan power.",
      fr: "L’œuvre vient d’une audience réelle, sans être un document diplomatique neutre. Elle résulte du point de vue de la mission française, de treize années de reconstruction mémorielle et des conventions du Salon. La présence souveraine du sultan coexiste avec un regard européen qui classe le pouvoir marocain.",
    },
  },
  {
    id: "medea",
    featured: true,
    image: "./assets/artworks/medea.jpg",
    source: "https://pba-opacweb.lille.fr/fr/notice/p-542-medee-furieuse-728613e5-a02a-41d0-ab08-21f722077595",
    date: "1838",
    category: "literature",
    medium: { zh: "布面油画", en: "Oil on canvas", fr: "Huile sur toile" },
    dimensions: "260 × 165 cm",
    collection: { zh: "里尔美术宫，里尔", en: "Palais des Beaux-Arts de Lille", fr: "Palais des Beaux-Arts de Lille" },
    title: { zh: "愤怒的美狄亚", en: "Medea About to Kill Her Children", fr: "Médée furieuse" },
    summary: {
      zh: "美狄亚抱住两个孩子并握刀躲入岩洞，戏剧最不可逆的行为尚未发生。德拉克洛瓦从1820年代起反复研究这一主题，最终用古典三角构图容纳母亲、保护者与杀人者无法分开的瞬间。",
      en: "Medea grips her two children and a knife inside a rocky shelter; the tragedy’s irreversible act has not yet occurred. Delacroix studied the subject from the 1820s, finally using a classical triangle to hold mother, protector, and killer in one indivisible moment.",
      fr: "Médée serre ses deux enfants et tient un couteau dans un abri rocheux ; l’acte irréversible n’a pas encore eu lieu. Delacroix travaille le sujet dès les années 1820 et emploie finalement un triangle classique pour rendre inséparables mère, protectrice et meurtrière.",
    },
    analysis: {
      zh: "三个身体构成紧绷金字塔，孩子向两侧逃离的动作却不断撕开中心。洞口强光打在肩、手臂和刀刃上，米开朗基罗式肌肉不表示稳定英雄性，而把心理冲突变为几乎过度的身体力量。",
      en: "Three bodies form a taut pyramid, repeatedly torn open by children escaping in opposite directions. Light strikes shoulder, arms, and blade; Michelangelesque musculature conveys not stable heroism but psychological conflict converted into almost excessive bodily force.",
      fr: "Les trois corps forment une pyramide tendue, déchirée par les enfants fuyant en sens opposés. La lumière frappe épaule, bras et lame ; la musculature michelangelesque ne signifie pas l’héroïsme stable, mais un conflit psychique devenu force corporelle presque excessive.",
    },
    context: {
      zh: "十九世纪评论常把美狄亚变成“失控女性”的恐惧形象，画作又以极强身体尊严抵抗纯粹怪物化。细读需要同时承认儿童面临的暴力、性别化判断，以及德拉克洛瓦对行动前心理裂变的兴趣。",
      en: "Nineteenth-century criticism often turned Medea into a fear of uncontrolled womanhood, while the painting’s bodily dignity resists simple monstrosity. A close reading must hold together violence toward the children, gendered judgement, and Delacroix’s interest in psychic fracture before action.",
      fr: "La critique du XIXe siècle fait souvent de Médée la peur d’une féminité incontrôlée, tandis que sa dignité corporelle résiste à la simple monstruosité. Il faut tenir ensemble la violence faite aux enfants, le jugement genré et l’intérêt de Delacroix pour la fracture psychique avant l’acte.",
    },
  },
  {
    id: "fanatics-tangier",
    featured: true,
    image: "./assets/artworks/fanatics-tangier.jpg",
    source: "https://artsandculture.google.com/asset/fanatics-of-tangier/GQFWfe9Fn0D95Q",
    date: "1837—1838",
    category: "travel",
    medium: { zh: "布面油画", en: "Oil on canvas", fr: "Huile sur toile" },
    dimensions: "95.6 × 128.6 cm",
    collection: { zh: "明尼阿波利斯艺术学院，明尼阿波利斯", en: "Minneapolis Institute of Art", fr: "Minneapolis Institute of Art" },
    title: { zh: "丹吉尔狂热者", en: "The Fanatics of Tangier", fr: "Les Convulsionnaires de Tanger" },
    summary: {
      zh: "德拉克洛瓦在1832年丹吉尔曾从遮蔽处观看伊萨维亚苏菲团体的仪式队列，数年后将记忆重构为冲入街道的人群。画面记录的不只是事件，也是一场受到观看距离限制的视觉经验。",
      en: "In Tangier in 1832, Delacroix watched an Aïssaoua Sufi procession from concealment, then reconstructed the memory years later as a crowd surging into the street. The painting records not only an event but a visual experience constrained by distance and access.",
      fr: "À Tanger en 1832, Delacroix observe à couvert une procession soufie des Aïssaoua, puis reconstruit ce souvenir quelques années plus tard en foule débouchant dans la rue. Le tableau consigne autant un événement qu’une expérience visuelle limitée par la distance et l’accès.",
    },
    analysis: {
      zh: "人群沿街道对角线喷涌而下，举起的手臂和白色衣褶把节奏切成短促脉冲。建筑没有提供安稳背景，而像漏斗一样压缩并释放运动；冷阴影与日照赭色制造突然显现的感觉。",
      en: "The crowd pours down the street diagonal, raised arms and white folds breaking rhythm into short pulses. Architecture acts not as stable backdrop but as a funnel compressing and releasing movement; cool shadow against sunlit ochre produces a sense of sudden apparition.",
      fr: "La foule déferle sur la diagonale de la rue ; bras levés et plis blancs découpent le rythme en impulsions brèves. L’architecture n’est pas un fond stable, mais un entonnoir qui comprime puis libère le mouvement ; ombre froide et ocre solaire créent une apparition soudaine.",
    },
    context: {
      zh: "“狂热者／痉挛者”是欧洲编目沿用的历史标题，不是对伊萨维亚仪式的中性解释。界面保留通行题名以便检索，同时明确它把苏菲宗教实践病理化、奇观化的殖民语言。",
      en: "‘Fanatics’ or ‘Convulsionists’ is the inherited European title, not a neutral account of Aïssaoua practice. The interface retains it for identification while making visible the colonial language that pathologised and spectacularised a Sufi ritual.",
      fr: "« Fanatiques » ou « Convulsionnaires » est un titre européen hérité, non une description neutre de la pratique aïssaoua. L’interface le conserve pour l’identification tout en signalant le langage colonial qui pathologise et spectacularise un rituel soufi.",
    },
  },
  {
    id: "jacob-angel",
    featured: true,
    image: "./assets/artworks/jacob-angel.jpg",
    source: "https://commons.wikimedia.org/wiki/File:Eug%C3%A8ne_Delacroix_%E2%80%94_Jacob_Wrestling_with_the_Angel.jpg",
    date: "1854—1861",
    category: "religion",
    medium: { zh: "油与蜡绘于灰泥墙面", en: "Oil and wax on plaster", fr: "Huile et cire sur enduit" },
    dimensions: "约751 × 485 cm",
    collection: { zh: "圣叙尔比斯教堂圣天使礼拜堂，巴黎", en: "Chapel of the Holy Angels, Saint-Sulpice, Paris", fr: "Chapelle des Saints-Anges, église Saint-Sulpice, Paris" },
    title: { zh: "雅各与天使搏斗", en: "Jacob Wrestling with the Angel", fr: "La Lutte de Jacob avec l’Ange" },
    summary: {
      zh: "圣叙尔比斯圣天使礼拜堂是德拉克洛瓦最漫长、也最消耗身体的公共工程之一。雅各在黎明前与天使搏斗的题材，被画家扩展为关于阻力、祝福与创造劳动的晚年壁画。",
      en: "The Chapel of the Holy Angels at Saint-Sulpice was among Delacroix’s longest and most physically demanding public projects. Jacob’s struggle with the angel before dawn becomes a late mural about resistance, blessing, and creative labour.",
      fr: "La chapelle des Saints-Anges à Saint-Sulpice compte parmi les chantiers publics les plus longs et les plus éprouvants de Delacroix. La lutte de Jacob avec l’ange avant l’aube devient une peinture tardive sur la résistance, la bénédiction et le travail créateur.",
    },
    analysis: {
      zh: "搏斗没有占据正中央：巨大树干、被抛下的衣物、远处行旅和前景武器共同延迟我们发现两具相扣身体。天使近乎静止，雅各斜向发力；力量由重量对抗重量，而不是靠夸张表情传达。",
      en: "The struggle is displaced from the centre. Vast trunks, abandoned garments, distant travellers, and foreground weapons delay our discovery of the locked bodies. The angel is almost still while Jacob drives diagonally; force is conveyed as weight against weight, not exaggerated expression.",
      fr: "La lutte est décentrée. Troncs immenses, vêtements abandonnés, voyageurs lointains et armes au premier plan retardent la découverte des corps noués. L’ange demeure presque immobile, Jacob pousse en diagonale : la force naît d’un poids opposé à un autre, non de l’expression outrée.",
    },
    context: {
      zh: "宗教题材不能自动证明正统信仰。德拉克洛瓦的日记把这项工程写成脚手架、潮湿墙面、疾病与反复修改的现实劳动；因此“搏斗”既可被神学阅读，也映照画家自身与材料和时间的缠斗。",
      en: "A religious subject does not automatically prove orthodoxy. Delacroix’s journal records scaffolding, damp walls, illness, and revision as material facts of the commission. The ‘struggle’ supports theological reading while reflecting the painter’s own contest with matter and time.",
      fr: "Un sujet religieux ne prouve pas automatiquement l’orthodoxie. Le Journal consigne échafaudages, murs humides, maladie et reprises comme réalités matérielles du chantier. La « lutte » se prête à la théologie tout en reflétant le combat du peintre avec la matière et le temps.",
    },
  },
];
