import { featuredWorks } from "./featured-works.js";

export const languages = ["zh", "en", "fr"];

export const ui = {
  zh: {
    brand: "德拉克洛瓦",
    nav: { life: "生平", works: "作品", timeline: "时间线", journal: "日志", sources: "资料" },
    search: "检索",
    searchTitle: "跨人物、作品、年代与资料检索",
    searchPlaceholder: "例如：1848、摩洛哥、乔治·桑",
    searchEmpty: "输入作品、人物、年份或主题。",
    searchNone: "没有直接结果。试试年代、作品类型，或返回时间线浏览。",
    match: "匹配原因",
    open: "打开",
    source: "来源",
    close: "关闭",
    offline: "当前离线：文字与已缓存图像仍可阅读，外部馆藏链接稍后再打开。",
    footerLeft: "研究型原型 · 原始材料、编辑解释与现代研究分层呈现",
    footerRight: "作品图像：博物馆开放记录与公共领域数字图像；首页肖像由用户提供",
    imageLoadError: "图像暂时无法载入；作品元数据与分析仍可阅读。",
    result: "件作品",
    all: "全部",
    categories: { history: "历史与公共寓言", literature: "文学", travel: "旅行与北非", portrait: "人物", religion: "宗教", late: "晚期" },
    masterwork: "代表作",
    backGallery: "返回画廊",
    enlarge: "放大作品",
    save: "收藏作品",
    saved: "已收藏",
    date: "年代",
    medium: "媒介",
    dimensions: "尺寸",
    collection: "收藏",
    rights: "图像权利",
    publicDomain: "公共领域",
    tabs: { overview: "这是什么", analysis: "形式分析", context: "语境与争议", observe: "观看实验" },
    evidence: "证据与来源",
    museumRecord: "查看作品来源记录",
    researchNote: "研究笔记",
    notePlaceholder: "记录你在远观、去色与局部观察之间发现的变化……",
    noteSaved: "笔记已保存在此浏览器",
    modeColor: "保留色彩",
    modeValues: "去色观察",
    modeBlur: "模糊轮廓",
    observation: "观看方式",
    contentUpdated: "内容核验：2026年8月",
    exactSource: "来源层级",
    edited: "经编辑的一手材料",
    original: "原始材料",
    contemporary: "同时代见证",
    modern: "现代研究",
  },
  en: {
    brand: "Delacroix",
    nav: { life: "Biography", works: "Works", timeline: "Timeline", journal: "Journal", sources: "Sources" },
    search: "Search",
    searchTitle: "Search across people, works, dates, and sources",
    searchPlaceholder: "Try: 1848, Morocco, George Sand",
    searchEmpty: "Enter a work, person, year, or theme.",
    searchNone: "No direct match. Try a date or work type, or browse the timeline.",
    match: "Why it matches",
    open: "Open",
    source: "Source",
    close: "Close",
    offline: "You are offline. Text and cached images remain available; collection links can be opened later.",
    footerLeft: "Research prototype · Primary material, editorial interpretation, and modern scholarship remain distinct",
    footerRight: "Work images: open museum records and public-domain digital images; homepage portrait supplied by the user",
    imageLoadError: "The image could not be loaded. Metadata and analysis remain available.",
    result: "works",
    all: "All",
    categories: { history: "History and public allegory", literature: "Literature", travel: "Travel and North Africa", portrait: "Portraiture", religion: "Religion", late: "Late work" },
    masterwork: "Masterwork",
    backGallery: "Back to gallery",
    enlarge: "Enlarge work",
    save: "Save work",
    saved: "Saved",
    date: "Date",
    medium: "Medium",
    dimensions: "Dimensions",
    collection: "Collection",
    rights: "Image rights",
    publicDomain: "Public domain",
    tabs: { overview: "What it is", analysis: "Formal analysis", context: "Context and debate", observe: "Viewing experiment" },
    evidence: "Evidence and sources",
    museumRecord: "Open the source record",
    researchNote: "Research note",
    notePlaceholder: "Record what changes between distant viewing, grayscale, and close observation…",
    noteSaved: "Saved in this browser",
    modeColor: "Keep colour",
    modeValues: "View in grayscale",
    modeBlur: "Blur contours",
    observation: "Viewing mode",
    contentUpdated: "Content checked: August 2026",
    exactSource: "Evidence level",
    edited: "Edited primary material",
    original: "Original material",
    contemporary: "Contemporary witness",
    modern: "Modern scholarship",
  },
  fr: {
    brand: "Delacroix",
    nav: { life: "Biographie", works: "Œuvres", timeline: "Chronologie", journal: "Journal", sources: "Sources" },
    search: "Rechercher",
    searchTitle: "Rechercher parmi les personnes, les œuvres, les dates et les sources",
    searchPlaceholder: "Par exemple : 1848, Maroc, George Sand",
    searchEmpty: "Saisissez une œuvre, une personne, une date ou un thème.",
    searchNone: "Aucun résultat direct. Essayez une date ou un type d’œuvre, ou consultez la chronologie.",
    match: "Pourquoi ce résultat",
    open: "Ouvrir",
    source: "Source",
    close: "Fermer",
    offline: "Vous êtes hors ligne. Les textes et les images en cache restent accessibles ; les liens externes pourront être ouverts plus tard.",
    footerLeft: "Prototype de recherche · Sources primaires, interprétations éditoriales et études modernes restent distinctes",
    footerRight: "Images des œuvres : notices muséales ouvertes et images numériques du domaine public ; portrait d’accueil fourni par l’utilisateur",
    imageLoadError: "L’image n’a pas pu être chargée. Les métadonnées et l’analyse restent disponibles.",
    result: "œuvres",
    all: "Toutes",
    categories: { history: "Histoire et allégorie publique", literature: "Littérature", travel: "Voyage et Afrique du Nord", portrait: "Portrait", religion: "Religion", late: "Œuvre tardive" },
    masterwork: "Chef-d’œuvre",
    backGallery: "Retour à la galerie",
    enlarge: "Agrandir l’œuvre",
    save: "Enregistrer l’œuvre",
    saved: "Enregistrée",
    date: "Date",
    medium: "Technique",
    dimensions: "Dimensions",
    collection: "Collection",
    rights: "Droits de l’image",
    publicDomain: "Domaine public",
    tabs: { overview: "De quoi s’agit-il ?", analysis: "Analyse formelle", context: "Contexte et débats", observe: "Expérience du regard" },
    evidence: "Preuves et sources",
    museumRecord: "Ouvrir la notice source",
    researchNote: "Note de recherche",
    notePlaceholder: "Notez ce qui change entre la vue lointaine, le noir et blanc et l’observation rapprochée…",
    noteSaved: "Enregistrée dans ce navigateur",
    modeColor: "Conserver la couleur",
    modeValues: "Voir en noir et blanc",
    modeBlur: "Estomper les contours",
    observation: "Mode d’observation",
    contentUpdated: "Contenu vérifié : août 2026",
    exactSource: "Niveau de preuve",
    edited: "Source primaire éditée",
    original: "Source originale",
    contemporary: "Témoignage contemporain",
    modern: "Étude moderne",
  },
};

export const home = {
  zh: {
    place: "1798—1863 · 巴黎",
    title: "欧仁·\n德拉克洛瓦",
    subtitle: "画家、作家，也是十九世纪法国最敏锐的观看者之一。",
    enter: "进入生平",
    caption: "欧仁·德拉克洛瓦，皮埃尔·珀蒂摄，1862年。",
  },
  en: {
    place: "1798—1863 · Paris",
    title: "Eugène\nDelacroix",
    subtitle: "Painter, writer, and one of the sharpest observers of nineteenth-century France.",
    enter: "Enter the biography",
    caption: "Eugène Delacroix, photographed by Pierre Petit, 1862.",
  },
  fr: {
    place: "1798—1863 · Paris",
    title: "Eugène\nDelacroix",
    subtitle: "Peintre, écrivain et l’un des observateurs les plus aigus de la France du XIXe siècle.",
    enter: "Entrer dans la biographie",
    caption: "Eugène Delacroix, photographié par Pierre Petit, 1862.",
  },
};

export const lifeIntro = {
  zh: {
    eyebrow: "生平 · 六个阶段",
    title: "不是一种风格，\n而是一生的矛盾",
    lede: "他自称古典主义者，却成为浪漫主义的核心人物；反感群众政治，却长期依靠国家委托塑造公共空间；热爱文学与音乐，也用色彩让绘画独立“思考”。",
    asideTitle: "65年",
    aside: "从督政府家庭到第二帝国学院院士，私人写作与公共事业始终并行。",
  },
  en: {
    eyebrow: "Biography · Six periods",
    title: "Not one style,\nbut a life of contradictions",
    lede: "He called himself a classicist yet became central to Romanticism; distrusted mass politics yet relied on state commissions to shape public space; loved literature and music while making colour think on its own terms.",
    asideTitle: "65 years",
    aside: "From a family of the Directory to membership of the Institut under the Second Empire, private writing and public work ran in parallel.",
  },
  fr: {
    eyebrow: "Biographie · Six périodes",
    title: "Non pas un style,\nmais une vie de contradictions",
    lede: "Il se disait classique tout en devenant une figure majeure du romantisme ; il se méfiait de la politique des foules tout en façonnant l’espace public grâce aux commandes d’État ; il aimait la littérature et la musique, mais fit penser la couleur par elle-même.",
    asideTitle: "65 ans",
    aside: "D’une famille du Directoire à l’Institut sous le Second Empire, l’écriture privée et l’œuvre publique avancent ensemble.",
  },
};

export const periods = [
  {
    id: "1798-1815",
    years: "1798—1815",
    zh: { label: "家庭与帝国", title: "在帝国兴衰中长大", summary: "家庭与革命、帝国官僚网络相连；古典教育、音乐与早期失亲共同形成了他的文化视野。", events: [["1798", "4月26日生于沙朗通-圣莫里斯。"], ["1806", "进入巴黎帝国中学，接受希腊罗马文学教育。"], ["1814", "母亲去世，家庭财务与继承纠纷加深不稳定感。"], ["1815", "拿破仑帝国终结；这一代人的决定性经验是复辟，而非亲历1789年革命。"]], note: "关于塔列朗可能是其生父的传说缺少文献证据，不能当作传记事实。" },
    en: { label: "Family and Empire", title: "Growing up through the rise and fall of Empire", summary: "A family tied to Revolutionary and imperial administration, a classical education, music, and early bereavement formed his cultural horizon.", events: [["1798", "Born on 26 April in Charenton-Saint-Maurice."], ["1806", "Entered the Lycée Impérial in Paris and studied Greek and Roman literature."], ["1814", "His mother died; financial and inheritance disputes deepened the family’s instability."], ["1815", "Napoleon’s Empire ended. Restoration, rather than direct experience of 1789, shaped his generation."]], note: "The claim that Talleyrand was his biological father lacks documentary support and should not be treated as fact." },
    fr: { label: "Famille et Empire", title: "Grandir avec l’essor et la chute de l’Empire", summary: "Une famille liée aux administrations révolutionnaire et impériale, l’éducation classique, la musique et les deuils précoces forment son horizon culturel.", events: [["1798", "Naissance le 26 avril à Charenton-Saint-Maurice."], ["1806", "Entrée au Lycée impérial à Paris ; apprentissage des littératures grecque et romaine."], ["1814", "Mort de sa mère ; les conflits financiers et successoraux fragilisent la famille."], ["1815", "Fin de l’Empire napoléonien. La Restauration, plus que l’expérience directe de 1789, marque sa génération."]], note: "L’hypothèse d’une paternité de Talleyrand ne repose sur aucune preuve documentaire et ne doit pas être présentée comme un fait." },
  },
  {
    id: "1816-1831",
    years: "1816—1831",
    zh: { label: "学院、英国与七月革命", title: "从学院训练到现代史画", summary: "他在学院制度内受训，却避开罗马大奖道路；文学、英国艺术和当代政治成为挑战历史画惯例的方法。", events: [["1816", "进入盖兰画室与巴黎美术学院。"], ["1822", "《但丁之舟》在沙龙亮相并被国家购藏。"], ["1824", "《希俄斯岛的屠杀》把当代战争带入宏大史画。"], ["1825", "赴伦敦约三个月，接触英国绘画、莎士比亚与拜伦。"], ["1830", "七月革命期间未参加街垒战；随后创作《自由引导人民》。"], ["1831", "《自由引导人民》在沙龙展出并由国家购藏。"]], note: "《自由引导人民》既是现代寓言，也曾因政治敏感而长期入库；它不能被简化为艺术家的参战记录。" },
    en: { label: "Academy, Britain, and July 1830", title: "From academic training to modern history painting", summary: "Trained within the academy yet avoiding the Prix de Rome route, he used literature, British art, and current politics to challenge the conventions of history painting.", events: [["1816", "Entered Guérin’s studio and the École des Beaux-Arts."], ["1822", "The Barque of Dante appeared at the Salon and was bought by the state."], ["1824", "The Massacre at Chios brought contemporary war into large-scale history painting."], ["1825", "Spent about three months in London, encountering British painting, Shakespeare, and Byron."], ["1830", "He did not fight on the barricades during the July Revolution; he later painted Liberty Leading the People."], ["1831", "Liberty Leading the People was shown at the Salon and purchased by the state."]], note: "Liberty Leading the People is a modern allegory that was also kept out of view for political reasons. It is not a record of the artist fighting in the revolution." },
    fr: { label: "Académie, Angleterre et Juillet 1830", title: "De la formation académique à la peinture d’histoire moderne", summary: "Formé au sein de l’Académie tout en évitant le prix de Rome, il mobilise la littérature, l’art anglais et l’actualité politique pour déplacer les conventions de la peinture d’histoire.", events: [["1816", "Entrée dans l’atelier de Guérin et à l’École des beaux-arts."], ["1822", "La Barque de Dante paraît au Salon et est achetée par l’État."], ["1824", "Les Massacres de Scio introduisent une guerre contemporaine dans la grande peinture d’histoire."], ["1825", "Séjour d’environ trois mois à Londres ; découverte de la peinture britannique, de Shakespeare et de Byron."], ["1830", "Il ne combat pas sur les barricades de Juillet ; il peint ensuite La Liberté guidant le peuple."], ["1831", "La Liberté guidant le peuple est exposée au Salon puis achetée par l’État."]], note: "La Liberté guidant le peuple est une allégorie moderne qui fut aussi mise en réserve pour des raisons politiques. Elle ne témoigne pas d’une participation du peintre aux combats." },
  },
  {
    id: "1832",
    years: "1832",
    zh: { label: "摩洛哥", title: "六个月的旅行，一生的视觉档案", summary: "随外交使团赴摩洛哥和阿尔及利亚的旅行带来速写、服饰、仪式与色彩记忆，也发生在法国征服阿尔及利亚的殖民语境中。", events: [["1月", "从土伦出发，经西班牙抵达丹吉尔。"], ["2月", "在丹吉尔记录犹太婚礼、家庭与城市生活。"], ["3月", "随使团前往梅克内斯觐见苏丹。"], ["6月", "经奥兰与阿尔及尔返法；在阿尔及利亚停留时间极短。"]], note: "速写本是快速助记，不是中立民族志；画家对当地人的分类和观看受外交使团、殖民扩张与进入权限限制。" },
    en: { label: "Morocco", title: "Six months of travel, a lifetime of visual memory", summary: "A diplomatic mission to Morocco and Algeria produced sketches of dress, ceremony, and colour, but unfolded within the colonial context of France’s conquest of Algeria.", events: [["January", "Left Toulon, travelled through Spain, and reached Tangier."], ["February", "Recorded a Jewish wedding, households, and city life in Tangier."], ["March", "Travelled with the mission to Meknes for an audience with the sultan."], ["June", "Returned through Oran and Algiers; his time in Algeria was extremely brief."]], note: "The sketchbooks are rapid memory aids, not neutral ethnography. Access, diplomatic purpose, and colonial expansion shaped whom and what he could see." },
    fr: { label: "Maroc", title: "Six mois de voyage, une vie de mémoire visuelle", summary: "La mission diplomatique au Maroc et en Algérie produit des croquis de costumes, de cérémonies et de couleurs, mais elle s’inscrit dans le contexte colonial de la conquête française de l’Algérie.", events: [["Janvier", "Départ de Toulon, passage par l’Espagne et arrivée à Tanger."], ["Février", "À Tanger, il note un mariage juif, des intérieurs et la vie urbaine."], ["Mars", "Voyage à Meknès avec la mission pour une audience auprès du sultan."], ["Juin", "Retour par Oran et Alger ; son séjour en Algérie est extrêmement bref."]], note: "Les carnets sont des aide-mémoire rapides, non une ethnographie neutre. L’accès, la mission diplomatique et l’expansion coloniale déterminent ce qu’il peut voir." },
  },
  {
    id: "1833-1847",
    years: "1833—1847",
    zh: { label: "国家工程", title: "让浪漫主义进入国家建筑", summary: "从波旁宫国王厅到两座议会图书馆，他与助手把色彩、文学和历史组织成大型公共装饰。", events: [["1833", "开始波旁宫国王厅装饰。"], ["1838", "获波旁宫众议院图书馆大型委托。"], ["1840", "开始卢森堡宫贵族院图书馆工程。"], ["1841", "《十字军进入君士坦丁堡》在沙龙展出。"], ["1847", "长期中断后恢复写日记。"]], note: "助手承担放大、转描、底画与部分执行；德拉克洛瓦负责构想、控制和最后修改。作者性应按具体工程与证据讨论。" },
    en: { label: "State commissions", title: "Bringing Romanticism into state architecture", summary: "From the Salon du Roi to the two parliamentary libraries, he and his assistants organised colour, literature, and history across vast public decorations.", events: [["1833", "Began the Salon du Roi decorations at the Palais Bourbon."], ["1838", "Received the major commission for the Chamber of Deputies library."], ["1840", "Began work on the Chamber of Peers library at the Luxembourg Palace."], ["1841", "The Entry of the Crusaders into Constantinople appeared at the Salon."], ["1847", "Resumed his journal after a long interruption."]], note: "Assistants enlarged designs, transferred drawings, and laid in paint; Delacroix devised, supervised, and retouched. Authorship must be discussed commission by commission." },
    fr: { label: "Commandes d’État", title: "Faire entrer le romantisme dans l’architecture d’État", summary: "Du Salon du Roi aux deux bibliothèques parlementaires, Delacroix et ses assistants organisent couleur, littérature et histoire dans de vastes décors publics.", events: [["1833", "Début du décor du Salon du Roi au Palais-Bourbon."], ["1838", "Commande majeure pour la bibliothèque de la Chambre des députés."], ["1840", "Début de la bibliothèque de la Chambre des pairs au palais du Luxembourg."], ["1841", "L’Entrée des croisés à Constantinople paraît au Salon."], ["1847", "Reprise du Journal après une longue interruption."]], note: "Les assistants agrandissent, reportent et ébauchent ; Delacroix conçoit, dirige et retouche. L’attribution doit être examinée chantier par chantier." },
  },
  {
    id: "1848-1857",
    years: "1848—1857",
    zh: { label: "社会活动与公共声望", title: "进入公共视野的十年", summary: "这不是政治激进主义的上升期，而是公共工程、制度角色、展览声望与社交网络集中累积的阶段。", events: [["1848", "二月革命后对社会主义与工人政治保持距离；在尚普罗赛创作花卉画。"], ["1849", "启动圣叙尔比斯教堂壁画工程。"], ["1850—1851", "完成卢浮宫阿波罗长廊天顶《阿波罗战胜巨蟒》。"], ["1851", "进入巴黎市议会，承担文化与城市公共事务角色。"], ["1855", "世界博览会集中展出三十余件作品，构成职业生涯回顾。"], ["1857", "多次落选后终于当选法兰西学会美术学院院士。"]], note: "公共声望上升不等于政治立场左转；1848年后他的阶级与社会立场趋于保守。" },
    en: { label: "Public life and recognition", title: "A decade of greater public visibility", summary: "This was not a turn toward political radicalism, but a concentrated accumulation of public commissions, institutional roles, exhibition prestige, and social networks.", events: [["1848", "Distanced himself from socialism and workers’ politics after the February Revolution; painted flowers at Champrosay."], ["1849", "Began the murals for Saint-Sulpice."], ["1850–1851", "Completed Apollo Slaying the Python on the ceiling of the Louvre’s Galerie d’Apollon."], ["1851", "Joined the Paris municipal council and assumed a role in cultural and civic affairs."], ["1855", "More than thirty works formed a career retrospective at the Exposition Universelle."], ["1857", "After repeated rejections, he was elected to the Académie des Beaux-Arts."]], note: "Greater public recognition did not mean a move to the political left; after 1848 his class and social positions became more conservative." },
    fr: { label: "Vie publique et reconnaissance", title: "Une décennie de visibilité publique", summary: "Il ne s’agit pas d’un tournant vers le radicalisme politique, mais d’une concentration de commandes publiques, de fonctions institutionnelles, de prestige d’exposition et de réseaux sociaux.", events: [["1848", "Après Février, il se tient à distance du socialisme et de la politique ouvrière ; il peint des fleurs à Champrosay."], ["1849", "Début des peintures murales de Saint-Sulpice."], ["1850–1851", "Achèvement d’Apollon vainqueur du serpent Python au plafond de la galerie d’Apollon du Louvre."], ["1851", "Entrée au conseil municipal de Paris et participation aux affaires culturelles de la ville."], ["1855", "Plus de trente œuvres forment une rétrospective à l’Exposition universelle."], ["1857", "Après plusieurs échecs, il est élu à l’Académie des beaux-arts."]], note: "La montée de sa reconnaissance publique ne signifie pas un déplacement vers la gauche ; après 1848, ses positions sociales deviennent plus conservatrices." },
  },
  {
    id: "1858-1863",
    years: "1858—1863",
    zh: { label: "圣叙尔比斯与晚年", title: "在身体衰弱中完成最后的壁画组", summary: "晚年的宗教壁画、重画旧题、日记与文章共同回到孤独、斗争、流放和创造者命运。", events: [["1859", "《奥维德在西徐亚人中》以流放者形象重访艺术家处境。"], ["1861", "圣叙尔比斯教堂圣天使礼拜堂壁画正式开放。"], ["1862", "发表最后一篇公开文章《夏勒》。"], ["1863", "8月13日在巴黎去世，葬于拉雪兹神父公墓。"]], note: "宗教题材不等于可简单确认的正统信仰；日记显示他的宗教态度复杂而多变。" },
    en: { label: "Saint-Sulpice and the final years", title: "Completing the final mural cycle as his health declined", summary: "Late religious murals, returns to earlier subjects, the journal, and essays converge on solitude, struggle, exile, and the fate of the creator.", events: [["1859", "Ovid among the Scythians revisited the artist’s position through an image of exile."], ["1861", "The Chapel of the Holy Angels murals at Saint-Sulpice opened to the public."], ["1862", "Published his last public essay, on Nicolas-Toussaint Charlet."], ["1863", "Died in Paris on 13 August and was buried at Père Lachaise Cemetery."]], note: "Religious subjects do not prove a simple orthodox faith; the journal records a complex and shifting position." },
    fr: { label: "Saint-Sulpice et dernières années", title: "Achever le dernier cycle mural malgré le déclin physique", summary: "Les peintures religieuses tardives, la reprise d’anciens sujets, le Journal et les essais convergent vers la solitude, la lutte, l’exil et le destin du créateur.", events: [["1859", "Ovide chez les Scythes reprend la figure de l’exilé pour penser la condition de l’artiste."], ["1861", "Ouverture au public des peintures de la chapelle des Saints-Anges à Saint-Sulpice."], ["1862", "Publication de son dernier article, consacré à Nicolas-Toussaint Charlet."], ["1863", "Mort à Paris le 13 août ; inhumation au cimetière du Père-Lachaise."]], note: "Les sujets religieux ne prouvent pas une foi orthodoxe simple ; le Journal révèle une position complexe et changeante." },
  },
];

export const worksIntro = {
  zh: { eyebrow: "作品 · 代表作与研究画廊", title: "从革命图像到颜色的记忆", lede: "先以十二件代表作建立德拉克洛瓦的公共形象，再用八件主题作品进入文学、旅行、色彩、宗教与晚年工作的细部。这里既看名作，也追问名作如何成为名作。", asideTitle: "20件", aside: "图像主要来自博物馆开放记录与公共领域数字资源；每件作品均保留可打开的来源记录。" },
  en: { eyebrow: "Works · Masterworks and study gallery", title: "From revolutionary image to remembered colour", lede: "Twelve masterworks establish Delacroix’s public profile; eight thematic works then deepen questions of literature, travel, colour, religion, and late practice. The gallery shows famous works while asking how they became famous.", asideTitle: "20 works", aside: "Images primarily come from open museum records and public-domain digital resources; every work retains an accessible source record." },
  fr: { eyebrow: "Œuvres · Chefs-d’œuvre et galerie d’étude", title: "De l’image révolutionnaire à la couleur remémorée", lede: "Douze chefs-d’œuvre établissent l’image publique de Delacroix ; huit œuvres thématiques approfondissent littérature, voyage, couleur, religion et pratique tardive. La galerie montre les œuvres célèbres tout en demandant comment elles le sont devenues.", asideTitle: "20 œuvres", aside: "Les images proviennent principalement de notices muséales ouvertes et de ressources numériques du domaine public ; chaque œuvre conserve une notice source accessible." },
};

const commonCollection = { zh: "大都会艺术博物馆，纽约", en: "The Metropolitan Museum of Art, New York", fr: "The Metropolitan Museum of Art, New York" };

const studyWorks = [
  {
    id: "basket-flowers", image: "./assets/artworks/basket-flowers.jpg", source: "https://www.metmuseum.org/art/collection/search/436175", date: "1848—1849", category: "late", medium: { zh: "布面油画", en: "Oil on canvas", fr: "Huile sur toile" }, dimensions: "107.3 × 142.2 cm", collection: commonCollection,
    title: { zh: "花篮", en: "Basket of Flowers", fr: "Panier de fleurs" },
    summary: { zh: "1848年革命后的巴黎动荡中，他退居尚普罗赛，快速画下一组并不“安静”的花卉。", en: "Amid the unrest of Paris after the 1848 Revolution, he withdrew to Champrosay and rapidly painted flowers that are anything but still.", fr: "Dans l’agitation parisienne qui suit la révolution de 1848, il se retire à Champrosay et peint rapidement des fleurs qui n’ont rien d’immobile." },
    analysis: { zh: "花束不是逐朵登记。高光、冷暖和暗部先构成整体节奏，个别花瓣随后才从色团中浮现。", en: "The bouquet is not an inventory of separate blooms. Highlights, warm and cool notes, and darkness first establish a total rhythm; individual petals emerge only afterward.", fr: "Le bouquet n’est pas l’inventaire de fleurs séparées. Rehauts, rapports chauds-froids et ombres établissent d’abord un rythme d’ensemble ; les pétales n’apparaissent qu’ensuite." },
    context: { zh: "这批花卉与1848年的政治退避并存。把它们只看作装饰，会忽略艺术家如何在公共危机中重建私人工作秩序。", en: "These flower paintings coincided with his political withdrawal in 1848. Treating them as mere decoration misses how he rebuilt a private working order during public crisis.", fr: "Ces fleurs coïncident avec son retrait politique en 1848. Les réduire à la décoration fait oublier la reconstruction d’un ordre de travail privé au cœur d’une crise publique." },
  },
  {
    id: "abduction-rebecca", image: "./assets/artworks/abduction-rebecca.jpg", source: "https://www.metmuseum.org/art/collection/search/438814", date: "1846", category: "literature", medium: { zh: "布面油画", en: "Oil on canvas", fr: "Huile sur toile" }, dimensions: "100.3 × 81.9 cm", collection: commonCollection,
    title: { zh: "丽贝卡被劫", en: "The Abduction of Rebecca", fr: "L’Enlèvement de Rébecca" },
    summary: { zh: "取材自司各特小说《艾凡赫》，文学在这里不是插图脚本，而是身体、马匹和色彩冲突的触发器。", en: "Drawn from Walter Scott’s Ivanhoe, literature serves not as an illustration script but as a trigger for clashing bodies, horses, and colour.", fr: "Tirée d’Ivanhoé de Walter Scott, la littérature n’est pas un scénario à illustrer mais le déclencheur d’un heurt de corps, de chevaux et de couleurs." },
    analysis: { zh: "倾斜的人体与马首将画面压向对角线。红、白、蓝并不只是服装颜色，而在拥挤空间中分配速度与重量。", en: "Tilted bodies and horses drive the composition along a diagonal. Red, white, and blue do more than describe costume: they distribute speed and weight through the crowded space.", fr: "Les corps inclinés et les chevaux lancent la composition sur une diagonale. Rouge, blanc et bleu ne décrivent pas seulement les costumes : ils distribuent vitesse et poids dans l’espace serré." },
    context: { zh: "画中被动女性与暴力救援延续了十九世纪文学和绘画中的性别结构；需要同时看到形式力量与叙事权力。", en: "The passive woman and violent rescue continue gender structures common to nineteenth-century literature and painting; formal force and narrative power must be read together.", fr: "La femme passive et le sauvetage violent prolongent des structures de genre propres à la littérature et à la peinture du XIXe siècle ; force formelle et pouvoir narratif doivent être lus ensemble." },
  },
  {
    id: "saada-preciada", image: "./assets/artworks/saada-preciada.jpg", source: "https://www.metmuseum.org/art/collection/search/336046", date: "1832", category: "travel", medium: { zh: "石墨稿上的水彩", en: "Watercolour over graphite", fr: "Aquarelle sur graphite" }, dimensions: "22.2 × 16.2 cm", collection: commonCollection,
    title: { zh: "萨阿达与女儿普雷西娅达", en: "Saada and Her Daughter Préciada", fr: "Saada et sa fille Préciada" },
    summary: { zh: "本-希莫尔家族为画家在丹吉尔提供了进入犹太家庭内部的机会；这张水彩保存了具体姓名，而不是泛化的“东方女性”。", en: "The Ben-Chimol family gave the artist access to a Jewish household in Tangier. This watercolour preserves individual names rather than a generic ‘Oriental woman’.", fr: "La famille Ben-Chimol lui donne accès à un foyer juif de Tanger. Cette aquarelle conserve des noms propres au lieu d’une « femme orientale » générique." },
    analysis: { zh: "轻薄水彩与石墨线互相保留，没有被后来的油画重量覆盖；姿势和服饰成为记忆索引。", en: "Thin watercolour and graphite remain mutually visible, unburdened by later oil paint; pose and clothing function as indexes of memory.", fr: "L’aquarelle légère et le graphite restent visibles l’un à travers l’autre, sans le poids de la peinture à l’huile ; pose et vêtement deviennent des index de mémoire." },
    context: { zh: "观看权限并不平等：穆斯林女性较难接近，犹太家庭则通过翻译者关系开放。作品既是相遇记录，也暴露殖民时期知识如何被生产。", en: "Access was unequal: Muslim women were harder to approach, while Jewish households opened through relationships with interpreters. The work records an encounter and exposes how colonial knowledge was produced.", fr: "L’accès est inégal : les femmes musulmanes sont difficiles à approcher, tandis que les foyers juifs s’ouvrent par les relations avec les interprètes. L’œuvre consigne une rencontre et révèle la fabrication du savoir colonial." },
  },
  {
    id: "ovid-scythians", image: "./assets/artworks/ovid-scythians.jpg", source: "https://www.metmuseum.org/art/collection/search/439631", date: "1862", category: "late", medium: { zh: "纸本油画，裱于木板", en: "Oil on paper, laid down on wood", fr: "Huile sur papier marouflé sur bois" }, dimensions: "32.1 × 50.2 cm", collection: commonCollection,
    title: { zh: "奥维德在西徐亚人中", en: "Ovid among the Scythians", fr: "Ovide chez les Scythes" },
    summary: { zh: "流放诗人被置于陌生共同体边缘；晚年的德拉克洛瓦借古代题材思考创造者的孤独与接纳。", en: "The exiled poet stands at the edge of an unfamiliar community; late Delacroix uses antiquity to consider the creator’s isolation and reception.", fr: "Le poète exilé se tient au bord d’une communauté étrangère ; le Delacroix tardif passe par l’Antiquité pour penser la solitude et l’accueil du créateur." },
    analysis: { zh: "低矮横幅把人物压进荒寒地景。中心不是英雄动作，而是围绕陌生人的缓慢聚集。", en: "The low horizontal format presses the figures into a bleak landscape. The centre is not heroic action but a slow gathering around a stranger.", fr: "Le format horizontal et bas enfonce les figures dans un paysage austère. Le centre n’est pas l’action héroïque, mais le lent rassemblement autour d’un étranger." },
    context: { zh: "“文明／野蛮”的古老二分仍在题材中运作。现代观看需要识别这种欧洲中心框架，而不把西徐亚人当成无历史的背景。", en: "The old binary of ‘civilised’ and ‘barbarian’ still structures the subject. A modern reading must identify that Eurocentric frame rather than turn the Scythians into a people without history.", fr: "L’ancienne opposition entre « civilisé » et « barbare » structure encore le sujet. Une lecture actuelle doit reconnaître ce cadre eurocentrique au lieu de réduire les Scythes à un peuple sans histoire." },
  },
  {
    id: "natchez", image: "./assets/artworks/natchez.jpg", source: "https://www.metmuseum.org/art/collection/search/436180", date: "1823—1824、1835", category: "literature", medium: { zh: "布面油画", en: "Oil on canvas", fr: "Huile sur toile" }, dimensions: "90.2 × 116.8 cm", collection: commonCollection,
    title: { zh: "纳奇兹人", en: "The Natchez", fr: "Les Natchez" },
    summary: { zh: "画作根据夏多布里昂小说构思，1820年代开始，搁置约十年后完成。", en: "Conceived from Chateaubriand’s fiction in the 1820s, the painting was set aside for roughly a decade before completion.", fr: "Conçu d’après Chateaubriand dans les années 1820, le tableau est laissé de côté pendant environ dix ans avant d’être achevé." },
    analysis: { zh: "新生儿与父母形成低处三角形，四周的巨大自然既保护又压迫。叙事高潮被改写成近乎静止的凝视。", en: "Infant and parents form a low triangle while the immense landscape both shelters and presses upon them. Narrative climax becomes an almost motionless act of looking.", fr: "Le nouveau-né et ses parents forment un triangle bas ; l’immense nature les protège autant qu’elle les écrase. Le sommet narratif devient un regard presque immobile." },
    context: { zh: "作品处理法国殖民暴力后的原住民命运，却通过欧洲文学想象发言。今天需要把同情、原始主义和缺失的原住民声音并置。", en: "The work addresses Indigenous lives after French colonial violence, but speaks through European fiction. Sympathy, primitivism, and absent Indigenous voices must be held together.", fr: "L’œuvre aborde des vies autochtones après la violence coloniale française, mais parle par une fiction européenne. Il faut tenir ensemble compassion, primitivisme et absence des voix autochtones." },
  },
  {
    id: "christ-tempest", image: "./assets/artworks/christ-tempest.jpg", source: "https://www.metmuseum.org/art/collection/search/436176", date: "约1853", category: "religion", medium: { zh: "布面油画", en: "Oil on canvas", fr: "Huile sur toile" }, dimensions: "50.8 × 61 cm", collection: commonCollection,
    title: { zh: "风暴中沉睡的基督", en: "Christ Asleep during the Tempest", fr: "Le Christ endormi pendant la tempête" },
    summary: { zh: "德拉克洛瓦多次重画这一题材：小船的剧烈倾斜与沉睡人物构成信仰和危机的悖论。", en: "Delacroix repeatedly returned to this subject: the violently tilting boat and sleeping figure produce a paradox of faith and crisis.", fr: "Delacroix reprend plusieurs fois ce sujet : la barque violemment inclinée et la figure endormie produisent un paradoxe de foi et de crise." },
    analysis: { zh: "浪头、船身和身体被同一斜线串联；基督的静止不是没有动作，而是全画运动的反向支点。", en: "Waves, hull, and bodies are linked by a single diagonal. Christ’s stillness is not an absence of action but the counterweight to the painting’s movement.", fr: "Vagues, coque et corps sont reliés par une même diagonale. L’immobilité du Christ n’est pas une absence d’action, mais le contrepoids du mouvement général." },
    context: { zh: "不能仅凭宗教题材断言画家的正统信仰。日记显示他持续思考内在精神、怀疑与艺术经验之间的关系。", en: "A religious subject alone cannot establish orthodox belief. The journal shows sustained reflection on inward spirituality, doubt, and artistic experience.", fr: "Un sujet religieux ne suffit pas à établir une foi orthodoxe. Le Journal montre une réflexion continue sur spiritualité intérieure, doute et expérience artistique." },
  },
  {
    id: "hamlet-mother", image: "./assets/artworks/hamlet-mother.jpg", source: "https://www.metmuseum.org/art/collection/search/436178", date: "1849", category: "literature", medium: { zh: "布面油画", en: "Oil on canvas", fr: "Huile sur toile" }, dimensions: "27.3 × 18.1 cm", collection: commonCollection,
    title: { zh: "哈姆雷特与母亲", en: "Hamlet and His Mother", fr: "Hamlet et sa mère" },
    summary: { zh: "莎士比亚不是一次性题材，而是贯穿版画与油画的心理剧场。", en: "Shakespeare was not a one-off subject but a psychological theatre spanning prints and paintings.", fr: "Shakespeare n’est pas un sujet ponctuel mais un théâtre psychologique traversant estampes et peintures." },
    analysis: { zh: "小尺幅压缩距离，床帐、黑衣和手势把争执变成封闭室内的心理回声。", en: "The small format compresses distance; bed curtain, black costume, and gesture turn confrontation into a psychological echo chamber.", fr: "Le petit format comprime la distance ; rideau du lit, vêtement noir et geste transforment l’affrontement en chambre d’écho psychologique." },
    context: { zh: "他晚期文学题材越来越关注女性、判断与死亡，但叙事仍由男性主人公的危机组织。", en: "His later literary subjects increasingly address women, judgement, and death, yet remain organised around the male protagonist’s crisis.", fr: "Ses sujets littéraires tardifs abordent davantage les femmes, le jugement et la mort, tout en restant organisés autour de la crise du protagoniste masculin." },
  },
  {
    id: "nohant-garden", image: "./assets/artworks/nohant-garden.jpg", source: "https://www.metmuseum.org/art/collection/search/436177", date: "约1842—1843", category: "portrait", medium: { zh: "布面油画", en: "Oil on canvas", fr: "Huile sur toile" }, dimensions: "45.4 × 55.2 cm", collection: commonCollection,
    title: { zh: "乔治·桑在诺昂的花园", en: "George Sand’s Garden at Nohant", fr: "Le Jardin de George Sand à Nohant" },
    summary: { zh: "友谊在这里不是人物肖像，而是一处共同生活、阅读与音乐记忆的地点。", en: "Friendship appears here not as a portrait but as a place carrying shared memories of life, reading, and music.", fr: "L’amitié apparaît ici non sous forme de portrait, mais comme un lieu chargé de souvenirs de vie, de lecture et de musique." },
    analysis: { zh: "低地平线和遮蔽小径把花园变成可进入的空间；松动笔触保留了现场感而非地形测绘。", en: "A low horizon and sheltered path make the garden enterable; loose handling preserves presence rather than topographic precision.", fr: "L’horizon bas et l’allée couverte rendent le jardin pénétrable ; la touche libre conserve une présence plutôt qu’une exactitude topographique." },
    context: { zh: "德拉克洛瓦与乔治·桑的书信涉及工作、疾病、文学、肖邦与互相支持。现存手稿集需与后期编目日期和编辑版本区分。", en: "Letters between Delacroix and George Sand address work, illness, literature, Chopin, and mutual support. The surviving manuscript collection must be distinguished from later catalogue dates and edited editions.", fr: "La correspondance entre Delacroix et George Sand traite du travail, de la maladie, de la littérature, de Chopin et du soutien mutuel. Il faut distinguer les manuscrits des datations de catalogue et des éditions ultérieures." },
  },
];

export const works = [...featuredWorks, ...studyWorks];

export const journal = {
  intro: {
    zh: { eyebrow: "日志 · 原文、译本与编辑层", title: "阅读一个画家如何观察自己", lede: "日记不是完整职业清单，也不是透明自传。它在日常记录、译本删节、作品往返与后世编辑之间形成多层文本。" },
    en: { eyebrow: "Journal · Original, translation, and editorial layers", title: "Reading how a painter observed himself", lede: "The journal is neither a complete professional register nor a transparent autobiography. It is a layered text of daily entries, abridged translations, works in progress, and later editing." },
    fr: { eyebrow: "Journal · Original, traductions et couches éditoriales", title: "Lire comment un peintre s’observe", lede: "Le Journal n’est ni un registre professionnel complet ni une autobiographie transparente. Il superpose notes quotidiennes, traductions abrégées, œuvres en cours et interventions éditoriales." },
  },
  periods: [
    { id: "1822", label: { zh: "1822—1824　青年日记", en: "1822–1824　Early journal", fr: "1822–1824　Journal de jeunesse" }, date: "1822—1824", title: { zh: "自律、雄心与厌倦", en: "Discipline, ambition, and ennui", fr: "Discipline, ambition et ennui" }, text: { zh: "最早的日记既记录阅读、工作和社交，也承担自我训练功能。它受到卢梭式告白传统影响，并不能被当成未经修饰的内心独白。", en: "The earliest journal records reading, work, and social life while functioning as self-discipline. Shaped by the confessional tradition of Rousseau, it is not an unedited interior monologue.", fr: "Le premier Journal consigne lectures, travail et sociabilité tout en servant de discipline personnelle. Marqué par la tradition de l’aveu rousseauiste, il n’est pas un monologue intérieur sans retouche." } },
    { id: "1832", label: { zh: "1832　摩洛哥旅途", en: "1832　Journey to Morocco", fr: "1832　Voyage au Maroc" }, date: "1832", title: { zh: "速记一场无法停止的观看", en: "Rapid notes from a gaze that would not stop", fr: "Notes rapides d’un regard incessant" }, text: { zh: "旅行记录保存服饰、仪式、音乐、建筑与颜色，但大量判断来自十九世纪欧洲分类语言。应把“他看见了什么”与“他如何被允许观看”并读。", en: "The travel entries preserve dress, ceremony, music, architecture, and colour, but many judgements use nineteenth-century European categories. What he saw must be read together with how he was allowed to see it.", fr: "Les notes conservent costumes, cérémonies, musique, architecture et couleurs, mais nombre de jugements passent par les catégories européennes du XIXe siècle. Il faut lire ensemble ce qu’il voit et les conditions qui lui permettent de voir." } },
    { id: "1847", label: { zh: "1847　重新开始", en: "1847　A new beginning", fr: "1847　Recommencement" }, date: "1847", title: { zh: "二十余年空白之后", en: "After a gap of more than twenty years", fr: "Après plus de vingt ans de silence" }, text: { zh: "1824至1847之间存在巨大的日记断裂。恢复写作后，身体、工作节奏、友谊、音乐和艺术判断更持续地交织在一起。", en: "A major break separates 1824 from 1847. When writing resumes, health, rhythm of work, friendship, music, and artistic judgement become more continuously intertwined.", fr: "Une rupture majeure sépare 1824 de 1847. À la reprise, santé, rythme du travail, amitié, musique et jugement artistique s’entrelacent avec davantage de continuité." } },
    { id: "1855", label: { zh: "1855　世界博览会", en: "1855　Exposition Universelle", fr: "1855　Exposition universelle" }, date: "1855", title: { zh: "在回顾展与公共工程之间", en: "Between retrospective and public work", fr: "Entre rétrospective et travaux publics" }, text: { zh: "这一年的记录把展览、工作、健康与人际往来交织起来。世界博览会使早期沙龙名作、东方题材与公共装饰进入同一职业回顾视野。", en: "The year’s entries interweave exhibition, work, health, and social life. The Exposition Universelle brought early Salon pictures, ‘Oriental’ subjects, and public decoration into a single career retrospective.", fr: "Les notes de l’année mêlent exposition, travail, santé et sociabilité. L’Exposition universelle réunit tableaux des premiers Salons, sujets « orientaux » et décors publics dans une même rétrospective de carrière." } },
    { id: "1863", label: { zh: "1856—1863　晚期记录", en: "1856–1863　Late entries", fr: "1856–1863　Dernières notes" }, date: "1856—1863", title: { zh: "衰弱、写作与最后的墙", en: "Decline, writing, and the final walls", fr: "Déclin, écriture et derniers murs" }, text: { zh: "晚期日记不断返回体力、孤独、声誉、艺术词典计划和圣叙尔比斯壁画。它让“晚年大师”叙事显出日常劳动与不确定性。", en: "The late journal repeatedly returns to stamina, solitude, reputation, the projected dictionary of art, and the Saint-Sulpice murals. It replaces the myth of the late master with daily labour and uncertainty.", fr: "Le Journal tardif revient sans cesse sur les forces physiques, la solitude, la réputation, le projet de dictionnaire et Saint-Sulpice. Le mythe du vieux maître laisse place au travail quotidien et à l’incertitude." } },
  ],
};

export const sourceIntro = {
  zh: { eyebrow: "资料 · 来源与版本", title: "每个结论都能回到出处", lede: "原始记录、书信、同时代评论、工作室回忆与现代研究不混成一个“权威声音”。出版年与内容覆盖分别记录。" },
  en: { eyebrow: "Sources · Evidence and editions", title: "Every claim can return to its source", lede: "Journal entries, letters, contemporary criticism, studio memoirs, and modern scholarship are not merged into one authoritative voice. Publication date and content coverage remain separate." },
  fr: { eyebrow: "Sources · Preuves et éditions", title: "Chaque proposition peut revenir à sa source", lede: "Journal, lettres, critique contemporaine, souvenirs d’atelier et recherches modernes ne se confondent pas en une seule voix d’autorité. Date de publication et période couverte restent séparées." },
};

export const sources = [
  {
    id: "journal", level: "edited", coverage: "1822—1863",
    name: { zh: "《德拉克洛瓦日记》", en: "The Journal of Eugène Delacroix", fr: "Journal d’Eugène Delacroix" },
    type: { zh: "经编辑的一手材料", en: "Edited primary material", fr: "Source primaire éditée" },
    edition: { zh: "多个通行本均为选本", en: "Several common editions are selections", fr: "Plusieurs éditions courantes sont des choix" },
    detail: { zh: "覆盖1822—1824、1832、1847、1849—1863等记录，但存在重大时间缺口。英译本删节程度不同，中文本经英译转译。", en: "Includes entries from 1822–24, 1832, 1847, and 1849–63, with major gaps. English editions abridge differently; the common Chinese text was relayed through English.", fr: "Comprend notamment 1822–1824, 1832, 1847 et 1849–1863, avec d’importantes lacunes. Les traductions anglaises abrègent différemment ; le texte chinois courant passe par l’anglais." },
  },
  {
    id: "sand-letters", level: "original", coverage: "1837—1863",
    name: { zh: "德拉克洛瓦致乔治·桑书信手稿", en: "Delacroix’s manuscript letters to George Sand", fr: "Lettres manuscrites de Delacroix à George Sand" },
    type: { zh: "原始书信", en: "Original letters", fr: "Lettres originales" },
    edition: { zh: "手稿集，馆藏数字化", en: "Digitised manuscript collection", fr: "Recueil manuscrit numérisé" },
    detail: { zh: "法国国家艺术史研究院藏Ms 236，共86件：85封德拉克洛瓦书信及卷首奥罗尔·洛特-桑鉴真信；第25号为抄本。", en: "INHA manuscript Ms 236 contains 86 items: 85 Delacroix letters plus Aurore Lauth-Sand’s authentication letter; item 25 is a copy.", fr: "Le manuscrit INHA Ms 236 compte 86 pièces : 85 lettres de Delacroix et une lettre d’authentification d’Aurore Lauth-Sand ; la pièce 25 est une copie." },
  },
  {
    id: "essays", level: "edited", coverage: "1829—1862",
    name: { zh: "《德拉克洛瓦论美术与美术家》", en: "Delacroix on Art and Artists", fr: "Écrits de Delacroix sur l’art et les artistes" },
    type: { zh: "死后编集文字", en: "Posthumously compiled writings", fr: "Écrits réunis après sa mort" },
    edition: { zh: "中文本2008年", en: "Chinese edition, 2008", fr: "Édition chinoise, 2008" },
    detail: { zh: "中文本经过法文、俄文重编与中文翻译链，另有两位译者并存和可证误译；适合思想导航，精确术语须回查法文。", en: "The Chinese text passes through French, Russian re-editing, and Chinese translation, with two translators and demonstrable errors. It is useful for orientation, not exact terminology.", fr: "Le texte chinois passe par une réédition russe puis une traduction chinoise, avec deux traducteurs et des erreurs vérifiables. Il oriente la pensée, mais ne garantit pas les termes exacts." },
  },
  {
    id: "baudelaire", level: "contemporary", coverage: "1845—1864",
    name: { zh: "波德莱尔《我看德拉克洛瓦》", en: "Baudelaire on Delacroix", fr: "Baudelaire sur Delacroix" },
    type: { zh: "同时代评论选集", en: "Selection of contemporary criticism", fr: "Choix de critique contemporaine" },
    edition: { zh: "中文本2005年", en: "Chinese edition, 2005", fr: "Édition chinoise, 2005" },
    detail: { zh: "围绕1863年长文重新编排，包含波德莱尔、勒内·于格、编者和德拉克洛瓦书信等不同作者层。高度党派且带时代偏见。", en: "Reorganised around the long essay of 1863 and containing distinct layers by Baudelaire, René Huyghe, the editor, and Delacroix. Partisan and historically situated.", fr: "Réorganisé autour du long texte de 1863 et composé de couches distinctes — Baudelaire, René Huyghe, l’éditrice et Delacroix. Un regard partisan et historiquement situé." },
  },
  {
    id: "cambridge", level: "modern", coverage: "1798—1863",
    name: { zh: "《德拉克洛瓦剑桥指南》", en: "The Cambridge Companion to Delacroix", fr: "Guide de Cambridge sur Delacroix" },
    type: { zh: "现代论文集", en: "Modern essay collection", fr: "Recueil d’études modernes" },
    edition: { zh: "出版于2001年", en: "Published in 2001", fr: "Publié en 2001" },
    detail: { zh: "十章从代际、浪漫主义、大众文化、殖民、色彩、古典传统、文学与写作切入。殖民与性别批判以第五章最集中。", en: "Ten essays address generation, Romanticism, popular culture, colonialism, colour, classicism, literature, and writing. Colonial and gender critique is concentrated in chapter five.", fr: "Dix essais abordent génération, romantisme, culture populaire, colonialisme, couleur, tradition classique, littérature et écriture. La critique coloniale et genrée se concentre au chapitre cinq." },
  },
  {
    id: "lee", level: "modern", coverage: "1798—1863",
    name: { zh: "西蒙·李《德拉克洛瓦》", en: "Simon Lee, Delacroix", fr: "Simon Lee, Delacroix" },
    type: { zh: "现代专著", en: "Modern monograph", fr: "Monographie moderne" },
    edition: { zh: "出版于2015年", en: "Published in 2015", fr: "Publié en 2015" },
    detail: { zh: "适合生平、作品和图像元数据骨架，也提供殖民与性别问题入口；书中仍有若干年代错误和英雄谱系式夸大，需交叉核验。", en: "Useful as a biographical and object-data framework and as an entry to colonial and gender questions; several date errors and heroic-genealogy claims require checking.", fr: "Utile pour l’ossature biographique, les œuvres et les questions coloniales ou genrées ; plusieurs erreurs de date et exagérations généalogiques exigent une vérification croisée." },
  },
];
